# Generated by Django 2.2.7 on 2022-12-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tok', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='users.User')),
                ('retoks', models.ManyToManyField(blank=True, related_name='retoks', to='users.User')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
