# Generated by Django 2.2.7 on 2022-12-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221201_2330'),
        ('toks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('tok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toks.Toks')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
