# Generated by Django 2.2.7 on 2022-12-02 13:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('toks', '0002_tokcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toks',
            name='id',
            field=models.CharField(default=users.models.generate_uuid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
