# Generated by Django 2.2.7 on 2023-01-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toks', '0004_auto_20221203_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='toks',
            name='created_by_username',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
