# Generated by Django 2.2.7 on 2023-01-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221204_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='users.User'),
        ),
    ]
